#!/usr/bin/perl 

# perl script to modify html file generated by the Feature Extraction software so the links are unix-based and path relevant.
# this is (i think) a defunct script, but i'm keeping it in - aaron vollrath 07MAY2009
use warnings;
use Cwd;

unless(@ARGV){
	print "You did not enter any command line arguments!";
	exit;
}
$dir = $ARGV[0];
#$dir = "/media/sdb2/13868/";
#print "$dir \n";
opendir(DIRH, $dir);
while ($file= readdir(DIRH)) {
	  next if ($file !~ /.html/);
	print "$file\n";
	$filename = $dir.$file;
	open(HTMLFILE, $filename) or die "Unable to open $filename: $!";
	@htmlfile = <HTMLFILE>;
	$htmlfile = join('',@htmlfile);
	#print $htmlfile;
	$htmlfile =~ s/.\/QCReport_Graphs/QCReport_Graphs/g;
	$htmlfile =~ s/QCReport_Graphs/.\/QCReport_Graphs/g;
	$htmlfile =~ s/\\/\//g;
	#print $htmlfile;
	close HTMLFILE;
	unless(open(HTMLFILE,">$filename")){
		print "Can't open $filename\n";
	}
	print HTMLFILE $htmlfile;
	close(HTMLFILE);
	
}
closedir DIRH; 

print "Done.";