<?php
/**
 * Please, do not edit this file. The configuration file for Debian
 * is located in the /etc/phpmyadmin directory.
 */
#include('/etc/phpmyadmin/config.header.inc.php');
# Sorry... i edited this for the edge distribution.  feel free to change this, but remember that any changes will be revoked on an update.
