<div id="navcontainer">

<ul id="globalnav">
	<li><a href="./users.php">EDGE Users</a></li>
	<li><a href="../bbclone/show_global.php?lng=en" target="_blank">Usage Stats</a></li>
	<li><a href="./MultipleTreatments.php">New Trx</a></li>
	<li><a href="./newexp.php">New Exp</a></li>
	<li><a href="./updatevals.php">Edit Trx Atts</a></li>
	<li><a href="./edittrx.php">Edit/Del Liver Trx</a></li>
	<li><a href="./editkidneytrx.php">Edit/Del Kidney Trx</a></li>
	<li><a href="./allfinalratios.php">All Final Ratios</a></li>
	<li><a href="./changetestuserlevel.php">Change Test User Level</a></li>
	<!--<li><a href="../classification.php">Classification</a></li>-->
	<li><a href="./clonelist.php">Clone Lists</a></li>
	<li><a href="./editusertrx.php">Edit User Trx</a></li>
</ul>
<p>
</p>
</div>
