<?php

$svgcolorarray = array("aqua", "black", "blue", "fuchsia", "gray", "green", "lime", "maroon",
			"navy", "olive", "purple", "red", "silver", "teal", "yellow");

$colorarray = array("red", "steelblue4", "green", "blue", "orange", "AntiqueWhite4", "black",
"darkolivegreen4", "darkorange", "deeppink", "deeppink4", "deepskyblue", "dimgray", "firebrick", "forestgreen",
"khaki3", "lightsalmon", "magenta2", "mediumorchid4", "olivedrab1", "peru",
"silver", "yellow", "slategray4", "wheat");

$markstyle = array(MARK_SQUARE, MARK_UTRIANGLE, MARK_DTRIANGLE, MARK_DIAMOND, MARK_CIRCLE,
MARK_FILLEDCIRCLE, MARK_CROSS, MARK_STAR, MARK_X, MARK_LEFTTRIANGLE, MARK_RIGHTTRIANGLE,
MARK_FLASH);
/*
Mark Styles....
   1. MARK_SQUARE, A filled square
   2. MARK_UTRIANGLE, A triangle pointed upwards
   3. MARK_DTRIANGLE, A triangle pointed downwards
   4. MARK_DIAMOND, A diamond
   5. MARK_CIRCLE, A circle
   6. MARK_FILLEDCIRCLE, A filled circle
   7. MARK_CROSS, A cross
   8. MARK_STAR, A star
   9. MARK_X, An 'X'
  10. MARK_LEFTTRIANGLE, A half triangle, vertical line to left (used as group markers for Gantt charts)
  11. MARK_RIGHTTRIANGLE, A half triangle, vertical line to right (used as group markers for Gantt charts)
  12. MARK_FLASH, A Zig-Zag vertical flash
*/

// The following arrays are used for gradient filling of bar plots....

$outercolor = array("navy", "forestgreen", "darkred", "purple3","gray5",
			"gold", "magenta", "darkorange", "gold3", "gray3", "palegreen4", "orchid4",
			"slateblue4", "indianred3", "yellow4", "firebrick1", "navajowhite4",
			"purple4", "tomato3", "royalblue4","navy","gray5","darkred",
			"gold", "magenta", "darkorange", "gold3");

$innercolor = array("lightsteelblue", "darkseagreen1", "salmon", "orchid2", "ivory2",
			"yellow", "papayawhip", "lightgoldenrod1", "khaki2", "ivory3", "darkseagreen3",
			"palevioletred1", "skyblue", "peachPuff1", "wheat1", "goldenrod1", "oldlace",
			"pink1", "palevioletred1", "green","lightsteelblue","ivory2", "salmon",
			"yellow", "papayawhip", "lightgoldenrod1", "khaki2");


?>
