<!-- the header -->
<BODY BGCOLOR="#FFFFFF" LINK="#000099" VLINK="#6666CC">
<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH=600>
<TR>
<TD WIDTH=218>
<P><A HREF="http://genome.oncology.wisc.edu/EDGE/default.php"><IMG SRC="GIFs/EDGE2.png" border=0 WIDTH=255 HEIGHT=120 ALIGN=top></A></P>
</TD>
<TD VALIGN=bottom align=bottom WIDTH=460>
<CENTER><span class="H1"><FONT SIZE="+3" FACE="Arial">Environmental
Database For Gene Expression</FONT></span><BR>
<P><BR>
<BR>
</P></CENTER>
</TD>
</TR>
</TABLE>
<TABLE BORDER=0 BGCOLOR="#666699" CELLSPACING=0 WIDTH=600>
<TR BGCOLOR="#666699">
<TD WIDTH=298>
<P><TABLE BORDER=0 BGCOLOR="#666699" WIDTH=596 HEIGHT=50>
<TR>
<TD ALIGN=center WIDTH=250>
<P><A HREF="estquery.php"><FONT FACE="Arial" COLOR="#FFFFFF">EST
Frequencies</FONT></A></P>
</TD>
<TD ALIGN=center WIDTH=250>
<P><A HREF="query.php"><FONT FACE="Arial" COLOR="#FFFFFF">cDNA
Microarrays</FONT></A></P>
</TD>
</TR>
</TABLE>
</P>
</TD>
</TR><!-- the search bar-->

</TABLE>
