<TD width="20%" VALIGN=top BGCOLOR="#9999CC">
<?php
require 'edge_login_form.php';
?>
<FONT FACE="Arial"><SPAN class="GUTTER1"></FONT>
<P><A HREF="EDGEWebSite/about_edge.php" class=GUTTER1><FONT FACE="Arial" COLOR="#FFCC66">About
EDGE</FONT><FONT FACE="Arial"><BR>
<SPAN class="GUTTER2"></FONT><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">General
and contact information</FONT></A><FONT FACE="Arial"><BR>
<BR>
<SPAN class="GUTTER1"></FONT><A HREF="EDGEWebSite/flow_chart.php" class=GUTTER1><FONT FACE="Arial" COLOR="#FFCC66">Project
Flow Chart</FONT><FONT FACE="Arial"><BR>
<SPAN class="GUTTER2"></FONT><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">From
library construction to microarray analysis. It's all
outlined!</FONT></A><FONT FACE="Arial"><BR>
<BR>
<SPAN class="GUTTER1"></FONT><A HREF="EDGEWebSite/protocols.php" class=GUTTER1><FONT FACE="Arial" COLOR="#FFCC66">Protocols</FONT><FONT FACE="Arial"><BR>
<SPAN class="GUTTER2"></FONT><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">Library
construction, sequencing, frequency analysis, microarray
construction, hybridization, and
analysis</FONT></A><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">.</FONT><FONT FACE="Arial"><BR>
<BR>
<SPAN class="GUTTER1"></FONT><A HREF="EDGEWebSite/submit_your_own.php" class=GUTTER1><FONT FACE="Arial" COLOR="#FFCC66">Submit
Your Own Gene Expression Data</FONT><FONT FACE="Arial"><BR>
<SPAN class="GUTTER2"></FONT><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">Contact
us for your own submission ideas and participation in the
project</FONT></A><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF"><BR>
</FONT><FONT FACE="Arial"><BR>
<SPAN class="GUTTER1"></FONT><A HREF="EDGEWebSite/submit_your_own_scripts.php"><FONT FACE="Arial" COLOR="#FFCC66">Submit
Your Own Scripts to the Archive</FONT><FONT FACE="Arial"><BR>
<SPAN class="GUTTER2"></FONT><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">Contact
us to submit your own scripts or programs to the archive and
contribute to the use of genomics in toxicology
</FONT></A><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF"><BR>
<BR>
</FONT><FONT FACE="Arial"><SPAN class="GUTTER1"></FONT><FONT FACE="Arial" COLOR="#FFCC66">Links
to Other Genomics Databases</FONT><FONT FACE="Arial"><BR>
<SPAN class="GUTTER2"></FONT><A HREF="http://www.ncbi.nlm.nih.gov/Database/index.html"><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">NCBI</FONT></A><FONT FACE="Arial"><BR>
</FONT><A HREF="http://www.expasy.ch/sprot/sprot-top.html"><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">Swiss-Prot</FONT></A><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF"><BR>
<BR>
</FONT><FONT FACE="Arial"><SPAN class="GUTTER1"></FONT><FONT FACE="Arial" COLOR="#FFCC66">Links
to Other Toxicology Sites</FONT><FONT FACE="Arial"><BR>
<SPAN class="GUTTER2"></FONT><A HREF="http://www.toxicology.org/"><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">Society
of Toxicology</FONT></A><FONT FACE="Arial"><BR>
</FONT><A HREF="http://ntp-server.niehs.nih.gov/"><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">National
Toxicology Program</FONT></A><FONT FACE="Arial"><BR>
</FONT><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF"><BR>
</FONT><span class="GUTTER2"><A HREF="http://www.atsdr.cdc.gov/toxfaq.html"><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF">ATSDR's
ToxFAQs</FONT></A><FONT SIZE="-1" FACE="Arial" COLOR="#FFFFFF"><BR>
</FONT></P>
</TD>
